zer0-os/zNS-dapp

.circleci/config.yml
package.json

Completes [this task](https://zer0.io/a/network/tasks/board/3ac44844-2b98-46e1-b29d-7886da72484f/b2fdeea5-a7d0-4897-a32b-503ecc55aabb)

Initial setup continuous integration with CircleCI

---

.circleci/config.yml
CODEOWNERS
CONTRIBUTING.md
package.json

- Add code owners file
- Add contributing guidelines
- Make linting work on master

Implement branching policy

---

CONTRIBUTING.md

Relates to [this task](https://zer0.io/a/network/tasks/board/3ac44844-2b98-46e1-b29d-7886da72484f/d8775f3b-36ca-43fa-8527-ce1feb0d809f)

Fix hotfix and feature branch naming examples

---

package-lock.json
src/components/css/color-variables.scss
src/components/css/topbar-global.scss
src/components/table/domains-global.tsx
src/components/topbar/topbar-global.tsx
src/index.css

topbar for latest ZNS mockups
lpscrypt

Work/lpscrypt/frontend 0.5

---

package-lock.json
src/components/css/profile.scss
src/components/table/NFT-View/approval.tsx
src/components/table/NFT-View/nestedNFT-view.tsx
src/components/table/NFT-View/nft-image.tsx
src/components/table/all-domains.tsx
src/components/table/child-view.tsx
src/components/table/domains-global.tsx
src/components/table/grid-view.tsx
src/components/table/newDrops.tsx
src/components/table/table-image-global.tsx
src/components/table/tableView-global.tsx
src/components/table/tableView.tsx
src/components/topbar/create.tsx
src/components/topbar/shop/claims.tsx
src/components/topbar/shop/owned.tsx
src/components/topbar/topbar-global.tsx
src/components/topbar/wallet.tsx
src/index.tsx
src/lib/hooks/provider-hooks.ts
src/lib/useDomainStore.ts
tsconfig.json

Relates to [this task](https://zer0.io/a/network/tasks/board/3ac44844-2b98-46e1-b29d-7886da72484f/77ad8942-f9c9-4247-aa43-42f88d104114)

Resolve remaining console warnings/errors on front end as appropriate

---

src/components/table/NFT-View/approval.tsx
src/components/table/NFT-View/nestedNFT-view.tsx
src/components/table/NFT-View/nft-view.tsx
src/components/table/NFT-View/purchaseModal.tsx
src/components/table/all-domains.tsx
src/components/table/child-view.tsx
src/components/table/domains-global.tsx
src/components/table/grid-view.tsx
src/components/table/newDrops.tsx
src/components/table/searchDomain.tsx
src/components/table/tableView-global.tsx
src/components/table/tableView.tsx
src/components/topbar/forms/set-image.tsx
src/components/topbar/profile/profile.tsx
src/components/topbar/shop/allOwned.tsx
src/components/topbar/shop/claims.tsx
src/components/topbar/shop/outGoingApproval.tsx
src/components/topbar/shop/owned.tsx
src/components/topbar/shop/shop.tsx
src/components/topbar/stakingModal.tsx
src/components/topbar/topbar-global.tsx
src/components/topbar/topbar.tsx
src/components/transferDomains.tsx

I went through and removed all unnecessary console.logs, imports, functions and declarations.

Clean Components 

---

src/components/table/NFT-View/approval.tsx
src/components/table/all-domains.tsx

I went through and removed all unnecessary imports, console.log, functions and declarations. Missed a few went back and cleaned them up

Cleaned Components 

---

src/components/table/NFT-View/css/nftpage.scss
src/components/table/NFT-View/nestedNFT-view.tsx
src/components/table/NFT-View/nft-image.tsx
src/components/table/NFT-View/nft-view.tsx
src/components/table/NFT-View/ntfpage.tsx
src/components/table/table/css/subdomains.scss
src/components/table/table/grid-image.tsx
src/components/table/table/grid-view.tsx
src/components/table/table/table-image-global.tsx
src/components/table/table/tableView-global.tsx
src/components/table/table/tableView.tsx

removed all mock data that is currently being received dynamically
left in mock data that is not yet available on the client

removed mock data

---

src/components/table/NFT-View/css/nftpage.scss
src/components/table/NFT-View/nestedNFT-view.tsx
src/components/table/NFT-View/nft-image.tsx
src/components/table/NFT-View/nft-view.tsx
src/components/table/NFT-View/ntfpage.tsx
src/components/table/domainView/child-view.tsx
src/components/table/domainView/domains-global.tsx
src/components/table/table/css/subdomains.scss
src/components/table/table/grid-image.tsx
src/components/table/table/grid-view.tsx
src/components/table/table/table-image-global.tsx
src/components/table/table/tableView-global.tsx
src/components/table/table/tableView.tsx
src/components/topbar/shop/shop.tsx
src/components/topbar/topbar/css/topbar-global.scss
src/components/topbar/topbar/topbar-global.tsx
src/index.css

this can also be merged into develop

 Lpscrypt/work/demo edits

---

package-lock.json
src/components/Enlist/Enlist.js
src/components/PreviewCard/PreviewCard-New.tsx
src/components/table/NFT-View/ntfpage.tsx
src/components/table/domainView/child-view.tsx
src/components/table/table/tableView.tsx
src/lib/useDomainStore.ts

- Fixed package lock json
- Fixed compile error
- creator and owner addresses
- fixed names on enlist modals

Zachary Support Changes

---

src/App.tsx
src/lib/addresses.ts
src/lib/providers/ChainSelectorProvider.tsx
src/lib/providers/EnlistProvider.tsx
src/lib/providers/SubgraphProvider.tsx
src/lib/useDomainStore.ts
src/pages/ZNS/ZNS.tsx

Refactored apollo into subgraph provider and exposed chain change ability

Allow for network changes in subgraph

---

public/index.html
src/components/Cards/PreviewCard/PreviewCard.module.css
src/components/Cards/PreviewCard/PreviewCard.tsx
src/components/ConnectToWallet/ConnectToWallet.tsx
src/components/CopyInput/CopyInput.js
src/components/Tables/DomainTable/DomainTable.module.css
src/components/ZNALink/ZNALink.tsx
src/containers/NFTView/NFTView.module.css
src/containers/NFTView/NFTView.tsx
src/lib/providers/MintProvider.tsx
src/pages/ZNS/ZNS.tsx
src/styles/main.css

See commit names for individual changes

Pre-release tweaks

---

src/App.tsx
src/components/MintPreview/MintPreview.tsx
src/containers/MintNewNFT/MintNewNFT.tsx
src/containers/MintNewNFT/sections/Staking.tsx
src/containers/MintNewNFT/sections/Summary.tsx
src/containers/MintNewNFT/types.ts
src/lib/addresses.ts
src/lib/hooks/useMint.ts
src/lib/hooks/useStakingController.tsx
src/lib/providers/MintProvider.tsx
src/lib/providers/StakingRequestProvider.tsx
src/lib/types.ts
src/pages/ZNS/ZNS.tsx

The mint modal will now place a staking request instead of minting a sub domain if you don't own the parent domain

Staking Requests can be placed through Mint Modal

---

src/lib/useDomainStore.ts
src/pages/ZNS/ZNS.tsx

Creating PR for the hyperlink fix, now it awaits until the query finish loading

Changed to await until the query finish the data fetch

---

src/lib/utils/index.ts

Created PR to change the upload to IPFS system, now it sends HTTPS POST request to the upload api endpoint

Changed to send HTTPS POST to backend instead of IPFS client

---

src/components/Tables/BidTable/BidTable.tsx
src/containers/NFTView/NFTView.tsx
src/lib/hooks/useZAuctionBaseApiUri.ts
src/lib/providers/BidProvider.tsx
src/lib/zAuction.ts

- Fixed some risky code which dealt with zAuction
- Simplified some zAuction interactions
- Updated adapters for new zAuction version

zAuction API Refactoring and Performance Increases

---

src/lib/zAuction.ts

Some minor refactoring of the zAuction API call Observer pattern

zAuction API performance refactor

---

src/components/ConnectToWallet/ConnectToWallet.tsx
src/lib/connectors.ts
src/lib/hooks/provider-hooks.ts
src/pages/ZNS/ZNS.tsx

Created PR to reconnect to wallets if user was connected before using localStorage

Reconnect - disconnect fix

---

src/components/Tables/DomainTable/HighestBid.tsx
src/components/Tables/DomainTable/NumBids.tsx
src/containers/MintNewNFT/MintNewNFT.module.css
src/containers/MintNewNFT/MintNewNFT.tsx
src/containers/MintNewNFT/sections/Summary.tsx
src/lib/hooks/useBasicController.tsx
src/lib/hooks/useZnsDomain.tsx
src/lib/providers/MintProvider.tsx
src/pages/ZNS/ZNS.tsx

- Added error status message when minting
- Fixed bug that didn't refresh domain table when a new domain was minted
- Fixed bug with Domain Table not updating bid data with new table rows cause react is rude

Minting Domain Bug Fixes & Polish

---

src/containers/MakeABid/MakeABid.module.css
src/containers/MakeABid/MakeABid.tsx

- Fixed it so status steps are displayed when submitting a bid
- Fixed bug when a user has 0 WILD tokens but tries to make a bid
- Displays error text for failures when trying to approve zAuction
- Shows error text if the user doesn't have enough Ether to use as gas
> ![image](https://i.imgur.com/Ke7X8Kr.png)

Polished UX flow for making a bid

---

src/containers/NFTView/NFTView.tsx

Changed to display the domain title instead of ZNA

Domain Title not being shown - fix

---

src/lib/addresses.ts
src/lib/ipfs-client.ts
src/lib/utils/index.ts

- Mainnet contract addresses
- Updated ZNS Backend Uri
- Removed old ipfs-client file

Launch Config

---

src/components/NavBars/TitleBar/TitleBar.module.css
src/components/NavBars/TitleBar/TitleBar.tsx
src/pages/ZNS/ZNS.tsx

Fixed some issues related to the global search bar overflow. Previously, it wasn't cutting off the list of domains in your search, so they would just hover over the UI awkwardly. Now it cuts them off nicely, and animates to show/hide.

Global search overflow issues

---

src/containers/NFTView/NFTView.tsx

Was taking the most recent bid, rather than highest

NFT View highest bid fix

---

src/components/Confirmation/Confirmation.module.css
src/components/Confirmation/Confirmation.tsx
src/components/Tables/RequestTable/RequestTable.tsx
src/containers/Request/Request.module.css
src/containers/Request/Request.tsx

Button display after push, a spinner and "fulfilling" or "approving"

Added loading indicators when fullfiling / approving

---

src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
src/lib/hooks/zNSDomainHooks.tsx

Added a poll interval of 5s to the query, and a timeout of 500 ms with a refetch after the transaction its confirmed

my domains refresh list after accept bid

---

src/containers/BidList/BidList.tsx
src/containers/MakeABid/MakeABid.tsx
src/containers/NFTView/NFTView.tsx
src/containers/Request/Request.tsx
src/lib/providers/CurrencyProvider.tsx
src/lib/tokenPrices.ts

Page wont render $WILD USD values if fails, and values are $0 in that case

Coingecko should not render USD $WILD values if fails

---

src/components/MintPreview/MintPreview.module.css

Wrapping inactive zNA span in Mint Preview 

---

public/index.html

Added Fathom analytics link to `<head>` in `index.html`

Added Fathom analytics link

---

public/index.html

Needed analytics ASAP, but we're on a slight lag with QA for the other features in `develop`. Fast-tracking the analytics link so we can have it now, then will run QA for the other fixes.

Fast-track Fathom analytics link to master

---

src/components/Overlay/Overlay.tsx
src/components/Profile/Profile.tsx
src/components/Tables/BidTable/BidTable.tsx
src/components/Tables/DomainTable/DomainTable.tsx
src/containers/NFTView/NFTView.tsx
src/pages/ZNS/ZNS.tsx

Fixing a few bugs that slipped through QA
1. Request To Mint modal was getting cut off on (vertically) small screens
2. Removed "My Bids" from Profile until it's fixed

Post Cloudinary bugfixes

---

src/components/NFTMedia/index.tsx

For some reason, the header request for Cloudinary links without the file extension was giving a 404, meaning the dapp thought there was no Cloudinary link. As a solution, we should always put the file extension when requesting header info from Cloudinary.

Fix for 404 bug when attempting to load Cloudinary links

---

src/containers/NFTView/NFTView.module.css

NFT view margin didn't get caught from weird commit history - pushing the fix

Removed NFT view margin

---

src/containers/flows/MintWheels/helpers.ts
src/containers/flows/MintWheels/index.tsx
src/containers/flows/MintWheels/labels.tsx
src/containers/flows/MintWheels/steps/Info/Info.tsx
src/containers/flows/MintWheels/steps/SelectAmount/SelectAmount.module.css
src/containers/flows/MintWheels/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/MintWheels/steps/SelectAmount/assets/check.svg
src/lib/contracts.ts
src/lib/providers/MintProvider.tsx
src/lib/wheelSale.ts

Draft while I work on it - just wanting the preview builds

Mint Wheels flow tweaks

---

package-lock.json
package.json
src/components/Confirmation/Confirmation.tsx
src/components/TransferPreview/TranferPreview.module.css
src/components/TransferPreview/TransferPreview.tsx
src/lib/providers/TransferProvider.tsx
src/lib/utils/timeCache.ts

Task - [Implement Husky to run Prettier on Git push](https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/93cbefb8-b17f-40c9-b00c-d53e56b96521)
The 1st commit is to prettier existing files, and once we merge this PR, we can trigger prettier automatically whenever we commit the changes.

Implement Husky to run Prettier on Git push

---

src/components/Banners/CountdownBanner/CountdownBanner.module.css
src/components/Banners/CountdownBanner/CountdownBanner.tsx
src/components/Banners/CountdownBanner/countdown.json
src/components/Banners/MintWheelsBanner/MintWheelsBanner.module.css
src/pages/ZNS/ZNS.tsx

Replaced countdown banner with Serenity banner

---

.circleci/config.yml
package.json
src/components/ArrowLink/ArrowLink.test.tsx
src/components/ArrowLink/ArrowLink.tsx
src/components/Buttons/FutureButton/FutureButton.test.tsx
src/components/Buttons/FutureButton/FutureButton.tsx
src/components/Member/Member.test.tsx
src/components/Member/Member.tsx

1. Summary:
- Created test files for 3 basic components (FutureButton, Member, ArrowLink)
- Updated CircleCI configuration to run tests when the code is updated
2. Task
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/77022c2e-cd90-45c7-b3c3-585546a3ecfd

Setup basic tests for 3 presentational components (01)

---

src/components/Cards/NFTCard/NFTCard.module.css
src/components/Cards/PreviewCard/PreviewCard.module.css
src/components/Cards/PreviewCard/PreviewCard.tsx
src/containers/other/NFTView/NFTView.module.css
src/containers/other/NFTView/NFTView.tsx

Summary:
Quick fix of css issues for NFT images.
(Question: I am not sure why we are using css and inline styles in jsx. We should choose one to keep code readability and quality. I recommend css(scss) only)
Task:
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/2ac47463-959e-49d2-85d9-6e632dfdac92

[FEATURE] Quick-fix image behavior  (4/10/21)

---

src/containers/other/NFTView/NFTView.tsx
src/lib/types.ts
src/lib/zns/queries.ts

Updated history with "from" and "to" parameters of transfers, fetched directly from subgraph

Updated history transfers with "from" and "to"

---

package-lock.json
package.json

**Summary**: 
Add `useAsyncEffect` from https://github.com/rauldeheer/use-async-effect

build: add async effect package

---

src/components/Tooltip/Tooltip.module.scss
src/components/Tooltip/Tooltip.tsx
src/containers/other/NFTView/NFTView.module.scss
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/assets/download.svg
src/containers/other/NFTView/assets/share.svg

Per title
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/6d415e14-917d-4e9d-a134-917f9ee6e8d4

Download button on NFT View

---

src/components/Cards/NFTCard/NFTCard.module.scss
src/components/Cards/NFTCard/NFTCard.tsx
src/components/NFTMedia/CloudinaryMedia.tsx
src/components/NFTMedia/NFTMedia.module.scss
src/components/NFTMedia/index.tsx
src/components/NFTMedia/types.ts
src/components/Tables/GenericTable/GenericTable.tsx

Hardcoded the aspect ratio of grid cards for more consistent images across the dapp

Hardcode domain aspect ratios for consistent image display

---

src/containers/other/NFTView/NFTView.tsx

Fixed a bug where some bids were missing in bid history, but counting towards the "highest bid" amount

Release 0.10.1

---

package.json
src/containers/flows/MintWheels/index.tsx

Decrease polling rate to Infura to 30s, rather than 5s

Infura 429 Fix

---

package.json
src/components/NFTMedia/CloudinaryMedia.tsx
src/containers/flows/MintWheels/steps/Info/Info.tsx
src/containers/flows/MintWheels/steps/Loading/Loading.tsx
src/containers/other/NFTView/NFTView.tsx
src/lib/providers/MintProvider.tsx

Added some images optimisations to decrease load on Cloudinary

Release 0.10.13 - Image optimisations

---

package.json
src/containers/flows/MintWheels/index.tsx

- Adjusted banner text to "Join our Discord. Next Wheels batch will start at 0.738 ETH."
- Temporarily disabled sale polling while we work on a way to make it less cumbersome on Infura

Release 0.10.12 - Banner changes, remove polling

---

package.json
src/containers/flows/MintWheels/index.tsx
src/containers/flows/MintWheels/labels.tsx

Previously halted the Wheels sale, we need to resume it now

Release 0.10.15 - Added sale countdown

---

package.json
src/containers/flows/MintWheels/helpers.ts
src/containers/flows/MintWheels/index.tsx

- Changed EthPerWheel constant to 0.738
- Added an event listener for "DomainMinted" events. This listener only attaches if a wallet is connected to save our Infura quota.

Release 0.10.16 - Polling and price changes

---

src/components/NavBars/FilterBar/FilterBar.module.scss
src/components/NavBars/FilterBar/FilterBar.tsx

Changed zna bar behavior to wait 10 pixels when going up, and duration of transition to 0.4s.
Let me know any improvement and will be fixed asap
LINK TO ZER0 CARD:
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/a80e2349-2c2b-434f-90f3-e82a34e2335d

Tweak ZNA bar scrolling behaviour

---

.env.sample
src/containers/other/NFTView/NFTView.tsx

**Note**: I updated the netlify environment variables with the current zns share url.

Share to twitter

---

package-lock.json
public/index.html
src/styles/main.scss

I've added a line to the header meta tag, to disable user scalability. 
And also, added touch-action to CSS to only enable x and y action for scrolling.

Disabled pinch zooming with two fingers.

---

src/containers/flows/MintWheels/helpers.ts
src/containers/flows/MintWheels/index.tsx
src/lib/addresses.ts
src/lib/wheelSale.ts

@Remscar made some changes to the existing sale flow:
- Added helpers for protocol change
- Switched contract address from the wheels sale contract to the cribs sale contract

Update Wheels flow to work with Cribs contract

---

src/containers/flows/WheelsRaffle/index.tsx

feat(cribs-raffle): fix minor issue with displaying remaining block in banner

---

src/containers/flows/MintWheels/index.tsx

Update public sale to 48 hrs from whitelist sale

---

package.json
src/containers/flows/MintWheels/index.tsx

Halts the cribs sale with proper messaging

Halt Cribs sale

---

package.json
src/containers/flows/MintWheels/index.tsx
src/containers/flows/WheelsRaffle/index.tsx
src/lib/wheelSale.ts

Updated timings and whitelist for new cribs sale

Cribs Relaunch

---

src/components/NFTMedia/index.tsx

[Link to associated Notion card:  
](https://www.notion.so/a6744db9bfc84af5b1e836a32efc4a94?v=ce42cd014f4b4bfcbd558b0bf4630cf5&p=541475ccc79a4998928f6ea358d6edcc)
-----

feat(nft-media): use ipfs gateway instead of fleek to check media type

---

src/containers/flows/MintWheels/index.tsx
src/containers/flows/WheelsRaffle/index.tsx
src/lib/addresses.ts
src/lib/wheelSale.ts

Release 0.10.27 - feat(crafts-launch): update kovan contact address

---

src/components/Buttons/IconButton/IconButton.test.tsx
src/components/Buttons/IconButton/IconButton.tsx
src/lib/ipfs.ts
src/pages/ZNS/ZNS.tsx

[CARD](https://www.notion.so/rational-nomads/FEATURE-Tests-for-Icon-Button-component-741a04c10e5646bb9cf72c351cfbd65c)
-----
Button Icon Component didn't have unit tests
Added unit test for button Icon component

Button Icon Unit Test

---

package.json
src/components/Artwork/Artwork.test.tsx
src/components/Artwork/Artwork.tsx

[Card](https://www.notion.so/rational-nomads/FEATURE-Tests-for-Artwork-component-b75f374f093444778ee877bfe3e1bcab)
-----
The Artwork component didn't have a unit test
Created unit test for Artwork

Artwork unit test

---

package.json
src/pages/ZNS/ZNS.tsx

Changes:
- Hide raffle banner in preparation for upcoming drop

Release 0.10.30 - Hide raffle banner

---

package-lock.json
package.json
src/containers/staking/Deposits/Deposits.tsx
src/lib/currency.ts

**Changes:**
- Added a "Total Staked USD" widget to the Deposits page - [Associated Notion Card](https://www.notion.so/Add-a-widget-to-Deposits-to-show-user-s-total-value-locked-in-USD-21112f728e894f04aa9ed725b3648bb9)
- Fixed a bug where dApp would crash on My Deposits page - [Associated Notion Card](https://www.notion.so/Fix-My-Deposits-page-crash-138ab13b61ae4c0ca5c70dea106b7844)

Release 0.2.0

---

package.json
src/components/Artwork/Artwork.tsx
src/containers/flows/MakeABid/MakeABid.tsx
src/containers/flows/WheelsRaffle/index.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/Request/Request.tsx
src/lib/metadata.ts
src/lib/types.ts

feat(kicks-drop): update the nft media to use animation_url if available

---

src/pages/ZNS/ZNS.tsx

feat(kicks-drop): hide banner as it is past 48 hrs of sale

---

src/components/Cards/PreviewCard/PreviewCard.tsx
src/components/Cards/PreviewCard/Previewcard.test.tsx
src/lib/ipfs.ts
src/pages/ZNS/ZNS.tsx

-----
PreviewCard component doesn't have unit test
Add unit test for previewCard component

Preview Card Unit Test

---

src/components/Artwork/Artwork.tsx
src/containers/flows/MakeABid/MakeABid.tsx
src/containers/flows/WheelsRaffle/index.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/Request/Request.tsx
src/lib/metadata.ts
src/lib/types.ts

[Associated Notion Card](https://www.notion.so/Air-Wild-S1-01c2af256984457c9e88987ab4225782)
-----

feat(kicks-drop): add sample times back for testing the mint flow

---

public/index.html
src/index.tsx

[Associated Notion Card](https://www.notion.so/9f3775679657499487a1a06dfa58d381?v=82d95bfda1c84891b4c063f7415e414d&p=a1688041c23c4c4786b9c8740fb71b7b)
-----

Fix multiple <head /> tag issue

---

src/containers/other/NFTView/NFTView.tsx

feat(domain-history): fix invalid urls for address in list

---

package.json
src/components/ConnectToWallet/ConnectToWallet.tsx
src/components/NavBars/TitleBar/TitleBar.tsx
src/components/Profile/Profile.tsx
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/containers/flows/MintWheels/index.tsx
src/containers/staking/Deposits/Deposits.tsx
src/lib/utils/domains.ts

- Fixed some broken navigation
- Changed "could not find Metamask" copy
- Removed Offers tab from Profile

0.11.0 Hotfixes

---

package.json
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx

feat(subdomain-card): fix issue with ZNA navigation in grid view

---

src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx

As per #369 
Had a difficult merge for some reason, so just moved changes to this PR

Accept Bid messaging improvements

---

src/components/Cards/PreviewCard/PreviewCard.tsx
src/components/Profile/Profile.tsx
src/containers/flows/MintWheels/steps/Approval/Approval.tsx
src/containers/flows/WheelsRaffle/index.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/staking/DepositTable/DepositTable.tsx
src/containers/staking/DepositTable/DepositTableProvider.tsx
src/containers/staking/StakePool/PoolDetails/PoolDetails.tsx
src/containers/staking/StakePool/StakePool.tsx
src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
src/containers/staking/StakingContainer/StakingContainer.tsx
src/containers/staking/flows/ClaimFlow/ClaimFlow.tsx
src/containers/staking/flows/ClaimFlow/steps/Claim/Claim.tsx
src/containers/staking/flows/StakeFlow/StakeFlow.tsx
src/containers/staking/flows/components/PoolData/PoolData.tsx
src/lib/hooks/provider-hooks.ts
src/lib/providers/staking/StakingSDKProvider.tsx
src/lib/providers/staking/StakingUserDataProvider.tsx
src/pages/ZNS/ZNS.tsx
src/store/index.ts

Fix eslint warnnings

---

package-lock.json
package.json
src/components/NFTMedia/index.tsx

MIME type fix

---

src/lib/utils/number.test.ts

[Associated Notion Card](https://www.notion.so/9f3775679657499487a1a06dfa58d381?v=82d95bfda1c84891b4c063f7415e414d&p=b4fd243ef0894bdb939cbf4d5c91ab74)
-----

Fix naming test files

---

package-lock.json
package.json

[Associated Notion Card](https://www.notion.so/Improve-My-Deposits-page-load-time-6cb0272481dc4d62b478a3b7aab5c497)
-----
Bugfix
My Deposits page was loading very slow because `zFI-SDK` was synchronously calling a series of async functions.
Updated to newest version of `zFI-SDK`, which batches async function calls.
This was just a dependency update 😊

fix: Improve My Deposits loading speed

---

src/containers/Tables/SubdomainTable/SubdomainTable.tsx
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx
src/containers/other/NFTView/NFTView.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Team-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=efac15603a454ffa99cdf531e695b55e)
-----
-----
This will need to be merged into Eric's branch ```feat/ericlow/edit-metadata-integration```

Fix to Domain Header selection condition & fix minor typos

---

package-lock.json
package.json
src/components/Buttons/TextButton/TextButton.module.scss
src/components/Buttons/TextButton/TextButton.test.tsx
src/components/Buttons/TextButton/TextButton.tsx
src/containers/staking/StakeModule/StakeModule.module.scss
src/containers/staking/StakeModule/StakeModule.tsx

[Associated Notion Card #1](https://www.notion.so/Add-MAX-button-to-inputs-d2a3359a284048f496c89e4792c746a6)
[Associated Notion Card #2](https://www.notion.so/Staking-Site-Issue-Can-t-Unstake2b4df7a96773482e858e1e4ff5c92e4a)
-----
Feature & Bugfix
MAX button described in #397.
When unstaking, the UI would not show a wallet prompt and users would be unable to unstake their funds.
MAX button described in #397.
Users can now unstake their funds.

hotfix: Fix unstaking, add MAX button

---

package-lock.json
package.json
src/pages/ZNS/ZNS.tsx

feat(pets-drop): hide the banner

---

package.json
src/components/StatsWidget/StatsWidget.module.scss
src/containers/flows/SetBuyNow/SetBuyNow.tsx
src/containers/other/NFTView/NFTView.module.scss
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/components/HistoryItem.tsx
src/pages/ZNS/ZNS.module.scss
src/pages/ZNS/ZNS.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Team-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=92c305d70ca044bca8f402f1ada837ad)
-----
Cancel button on zAuction Approval step of set/edit Buy Now flow not working as expected.
Missing key console errors
Responsive design breaks
Cancel button on zAuction Approval step of set/edit Buy Now flow working as expected.
Missing key console error updated and resolved
Responsive design breaks update and resolved

[Bugs] Fix cancel button on zAuction Approval step of Buy Now & Missing key console errors

---

src/lib/hooks/useBidProvider.tsx

[Associated Notion Card](https://www.notion.so/Accept-Bid-Bug-76a2d65c6d384ec187acfcc623635bd7)
-----

feat(accept-bid): use zauction sdk method to accept bid

---

src/containers/other/NFTView/components/NFT.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=23e5f78895e6478eaed4a9e1ba543782)
-----
Bugfix
As outlined by @domw30 here
https://www.loom.com/share/e6b267d132674742a96ebdaadf61bd47
Remedies for @domw30's feedback. In short, the Your Bid section hides when expected.

fix: Change logic for hiding Your Bid in NFT View

---

package.json
src/containers/other/NFTView/NFTView.tsx

[Associated Notion Card](https://www.notion.so/Remove-3-from-HistoryItem-47e4e17486774861a22af233f2f27d50)
-----
Bugfix
There was a 3 prepended to wallet addresses for sale events in NFT View.
No more 3.

hotfix: Remove 3 from HistoryItem

---

src/lib/metadata.ts

[Associated Notion Card](https://www.notion.so/Fix-missing-row-button-c0cdb0a1b6714057b9becd4c0c4fcc86)
-----

Fix to show bid button by setting isBiddable as true as default

---

package-lock.json
package.json
src/lib/addresses.ts

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=c6681901281e410d8df92fe05cea7f5f)
-----
Accept bid transaction failing and missing data due to outdated zAuction rinkeby contract address & out of date zns-sdk version.
Bumped zns-sdk version and updated contract address. Along with protocol changes this will fix the issues.

Bump @zero-tech/zns-sdk and update rinkeby zAuction contract address to resolve missing data & accept bid bug

---

src/components/TransferPreview/TransferPreview.tsx
src/containers/PageContainer/index.tsx
src/containers/flows/MintNewNFT/MintNewNFT.tsx
src/containers/flows/MintNewNFT/sections/Summary.tsx
src/lib/utils/domains.ts

[Associated Notion Card](https://www.notion.so/Fix-incorrect-zNAs-when-minting-and-transferring-d2ee64c53f2e4e2a94f26c62f1a0adce)
-----
Bugfix
Mint modal and Transfer dialog both show incorrect zNAs (per Notion card).
Fixed zNAs.

bug: Fix incorrect zNAs

---

src/components/Buttons/FutureButton/FutureButton.tsx
src/components/ScrollToTop/ScrollToTop.tsx
src/components/index.js
src/constants/notifications.ts
src/containers/PageContainer/PageContainer.constants.ts
src/containers/PageContainer/PageContainer.module.scss
src/containers/PageContainer/elements/HomeIcon/HomeIcon.tsx
src/containers/PageContainer/elements/HomeIcon/_home-icon.module.scss
src/containers/PageContainer/elements/HomeIcon/index.ts
src/containers/PageContainer/elements/Modals/Modals.tsx
src/containers/PageContainer/elements/Modals/index.ts
src/containers/PageContainer/elements/index.ts
src/containers/PageContainer/index.tsx
src/lib/hooks/useDidMount.ts
src/lib/hooks/useNotification.ts
src/lib/hooks/usePageWidth.ts
src/lib/hooks/usePrevious.ts
src/lib/hooks/useUpdateEffect.ts
src/lib/hooks/useWillUnmount.ts
src/styles/main.scss

[Associated Notion Card](https://www.notion.so/dcf93eee667d4edeac4b2a927d211551?v=0fbbeae3210b49af8266e3495e7d8ba5&p=af6e662b7ae442e299e1c74138fb4f63)
-----

refactor: simplify page container

---

package-lock.json
package.json

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=4bad4e219d1541e08ba3d71926941d29)
-----
- Bugfix
Flow not working correctly.
Flow working as expected.
[Loom Demo](https://www.loom.com/share/94cfbe3f4a974702811d632c57b72e37)

bug: Update zAuction SDK to resolve Make a bid flow issues

---

src/lib/metadata.ts

[Associated Notion Card](https://www.notion.so/zerotech/dcf93eee667d4edeac4b2a927d211551?v=0fbbeae3210b49af8266e3495e7d8ba5&p=a425aef5fc814730803f102a276a3562)
-----

Make dApp read ‘stakingrequests’ and ‘stakingRequests’

---

src/containers/flows/MakeABid/MakeABid.tsx
src/containers/other/NFTView/NFTView.tsx
src/lib/hooks/useDomainMetadata.tsx
src/lib/hooks/useZnsDomain.tsx
src/lib/metadata.ts

[Associated Notion Card](https://www.notion.so/zerotech/dcf93eee667d4edeac4b2a927d211551?v=0fbbeae3210b49af8266e3495e7d8ba5&p=fbbbd06c8e2d438ebdee1312b6746247)
-----

Use domain metadata parsing at one place

---

src/lib/hooks/useBidProvider.tsx

Remove console log on bid steps

---

src/containers/other/NFTView/NFTView.tsx

[Associated Notion Card](https://www.notion.so/zerotech/NFT-Name-not-appearing-in-NFT-View-e7593735b3774149871611632b53a597)
-----
Bugfix
NFT title would not show up in NFT View.
NFT title now shows up in NFT View.

fix: Use proper metadata title in NFT View

---

package-lock.json
package.json
src/lib/useDomainSearch.tsx

[0.13.0 Release testing](https://www.notion.so/zerotech/0-13-0-Release-testing-88348931b0234f008deb032382fdfbb4)
-----

feat(domain-search): fix issue with domain search

---

src/containers/PageContainer/elements/Header/elements/SearchDomains/SearchDomains.constants.ts
src/containers/PageContainer/elements/Header/elements/SearchDomains/SearchDomains.tsx
src/containers/PageContainer/elements/Header/elements/SearchDomains/_search-domains.scss
src/containers/PageContainer/elements/Header/elements/SearchDomains/hooks/useSearchDomainsHandlers.ts

[Associated Notion Card](https://www.notion.so/zerotech/0-13-0-Release-testing-88348931b0234f008deb032382fdfbb4?p=3f5b93c645e946df8b37229a520157d7)
-----

Fix header searching sticky issue

---

src/components/Tables/GenericTable/GenericTable.tsx
src/pages/ZNS/ZNS.tsx

fix(grid-view): enforce grid view in mobile irrespective of domain setting value

---

src/components/Overlay/Overlay.tsx
src/components/Wizard/Presets/Buttons.tsx
src/components/Wizard/Presets/Confirmation.tsx
src/components/Wizard/Wizard.tsx
src/containers/DAO/DAOContainer.tsx
src/containers/DAO/pages/MintDAO/MintDAO.constants.ts
src/containers/DAO/pages/MintDAO/MintDAO.helpers.tsx
src/containers/DAO/pages/MintDAO/MintDAO.test.tsx
src/containers/DAO/pages/MintDAO/MintDAO.tsx
src/containers/DAO/pages/MintDAO/MintDAO.types.ts
src/containers/DAO/pages/MintDAO/MintDAOButton.tsx
src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.constants.ts
src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.module.scss
src/containers/DAO/pages/MintDAO/elements/MintDAOForm/MintDAOForm.tsx
src/containers/DAO/pages/MintDAO/elements/index.ts
src/containers/DAO/pages/MintDAO/index.ts
src/lib/hooks/useManyClickHandlers.ts

[Associated Notion Card](https://www.notion.so/zerotech/Make-static-Create-DAO-flow-a12ca1c2210149e2a0a763e1b12b346f)
-----
Feature
There was no way to create a DAO.
Added a modal for creating a new DAO per Figma.
This is currently just a static element - real data will be used when SDK is integrated.

feat: static "Create A DAO" flow

---

src/containers/PageContainer/elements/Header/elements/ConnectWalletButton/_connect-wallet-button.scss
src/containers/flows/MakeABid/MakeABid.tsx

[Associated Notion Card](https://www.notion.so/zerotech/0-13-0-Release-testing-88348931b0234f008deb032382fdfbb4)
-----

hotfix: minor Connect Button fix

---

src/components/ArrowLink/ArrowLink.test.tsx
src/components/ArrowLink/ArrowLink.tsx
src/components/Preview/Preview.module.scss
src/components/Preview/Preview.tsx
src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
src/pages/ZNS/ZNS.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Sceen-Market-Preview-6de9ea13131e4ed0aee43efbba92cc0f)
-----
Feature
Preview didn't perfectly match Figma.
Preview perfectly matches Figma.

feat: Adjust Preview styles to match Figma

---

src/components/ArrowLink/ArrowLink.test.tsx
src/components/ArrowLink/ArrowLink.tsx
src/components/Preview/Preview.module.scss
src/components/Preview/Preview.tsx
src/components/Tooltip/Tooltip.module.scss
src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
src/pages/ZNS/ZNS.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Component-Tooltip-b7136555f5d046b4bcdba73e6632e46b)
-----
Feature
Tooltip did not match Figma
Tooltip matches Figma

feat: Tooltip adjustments

---

src/components/Image/Image.tsx
src/containers/DAO/pages/Container.module.scss
src/containers/DAO/pages/DAOList/DAOList.tsx
src/containers/DAO/pages/DAOPage/DAOPage.module.scss
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/DAO/pages/DAOPage/Transactions/Transactions.helpers.tsx
src/containers/DAO/pages/DAOPage/Transactions/Transactions.tsx

fix: zDAO MVP feedback 3

---

package-lock.json
package.json
src/lib/utils/domains.ts

Fix regex issue on safari

---

src/lib/ipfs.ts

[Associated Notion Card](https://www.notion.so/zerotech/dcf93eee667d4edeac4b2a927d211551?v=0fbbeae3210b49af8266e3495e7d8ba5&p=74730b67d1e645b6ababf7b78a7584cc)
-----

fix: hash parsing from IPFS url

---

src/containers/other/NFTView/elements/NFT/NFT.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/Safari-text-bug-58254cf668cb4783813a04a80d36bb07)
-----
Bugfix
When scrolling on NFT View in iOS Safari, content would disappear until scrolling has stopped for a few seconds.
Content no longer disappears when scrolling on NFT View.
[Resource](https://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela)

fix: weird Safari iOS "disappearing content" bug

---

package.json
src/containers/other/NFTView/elements/NFT/NFT.module.scss
src/lib/ipfs.ts

- Fix some broken regex
- Fix disappearing content bug in Safari iOS

Release 0.14.2

---

package-lock.json
src/containers/flows/MintDropNFT/helpers.ts
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/Raffle/index.tsx

feat(mint-drop): update banner to support transition mode and countdown during private sale

---

src/containers/flows/MintDropNFT/helpers.ts
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/Info/Info.tsx

feat(mint-drop): remove countdown for public sale banner

---

package-lock.json
package.json
src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.module.scss
src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.tsx
src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
src/containers/flows/MintDropNFT/helpers.ts
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/Approval/Approval.tsx
src/containers/flows/MintDropNFT/steps/Finished/Finished.tsx
src/containers/flows/MintDropNFT/steps/Info/Info.tsx
src/containers/flows/MintDropNFT/steps/InsufficientFunds/InsufficientFunds.tsx
src/containers/flows/MintDropNFT/steps/Loading/Loading.tsx
src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/MintDropNFT/types.ts
src/containers/flows/Raffle/RaffleRegistration/RaffleRegistration.tsx
src/containers/flows/Raffle/RaffleRegistration/index.tsx
src/containers/flows/Raffle/WaitlistRegistration/WaitlistRegistration.tsx
src/containers/flows/Raffle/index.tsx
src/lib/addresses.ts
src/lib/hooks/sdk/useZSaleSdk.tsx
src/lib/hooks/useMint.ts
src/pages/ZNS/ZNS.tsx

Just toggling on the drop banner!

feat: Show Beasts banner

---

package.json
src/components/NFTMedia/config.ts
src/containers/flows/MintDropNFT/index.tsx

Removed Cloudinary version number from template URL, as it was giving some 404s

hotfix: Cloudinary 404

---

package-lock.json
src/containers/DAO/DAOContainer.tsx
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/Tables/SubdomainTable/SubdomainTable.tsx
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx
src/containers/staking/StakingContainer/StakingContainer.tsx
src/lib/providers/staking/StakingSDKProvider.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dcf93eee667d4edeac4b2a927d211551?v=0fbbeae3210b49af8266e3495e7d8ba5&p=1963871f88c04af5bf6e83414505b4d2)
-----

Remove eslint warnings and browser console logs

---

package.json
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/steps/Info/Info.tsx

Hotfix - fixes issue where user eligibility was inaccurate depending on when the user connected their wallet

feat(mint-drop): handle wallet not connected scenario

---

src/containers/other/NFTView/elements/Actions/Actions.mocks.ts
src/containers/other/NFTView/elements/Actions/Actions.test.tsx
src/containers/other/NFTView/elements/Actions/Actions.tsx

[Associated Notion Card](https://www.notion.so/zerotech/0-15-0-Reskin-b82bd575da3e48b29a0753ab410e4549?p=441d9c92ded046c1b0b5f1c02c8de030)
-----
- Bugfix

Fix NFT no-bids section

---

package-lock.json
package.json
src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.module.scss
src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.tsx
src/components/NFTMedia/config.ts
src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
src/containers/flows/MintDropNFT/helpers.ts
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/Approval/Approval.tsx
src/containers/flows/MintDropNFT/steps/Finished/Finished.tsx
src/containers/flows/MintDropNFT/steps/Info/Info.tsx
src/containers/flows/MintDropNFT/steps/InsufficientFunds/InsufficientFunds.tsx
src/containers/flows/MintDropNFT/steps/Loading/Loading.tsx
src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/MintDropNFT/types.ts
src/containers/flows/Raffle/RaffleRegistration/RaffleRegistration.tsx
src/containers/flows/Raffle/RaffleRegistration/index.tsx
src/containers/flows/Raffle/WaitlistRegistration/WaitlistRegistration.tsx
src/containers/flows/Raffle/index.tsx
src/lib/addresses.ts
src/lib/hooks/sdk/useZSaleSdk.tsx
src/lib/hooks/useMint.ts
src/lib/ipfs.ts
src/pages/ZNS/ZNS.tsx

Bringing some `master` hotfixes back into `develop`!

chore: master -> develop

---

package.json
src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
src/containers/flows/MintDropNFT/helpers.ts
src/lib/hooks/sdk/useZSaleSdk.tsx

feat(mint-drop): update config to set max allowed purchase for public sale

---

package.json
src/pages/ZNS/ZNS.tsx

feat(mint-drop): hide banner

---

src/components/Buttons/FutureButton/FutureButton.test.tsx
src/components/Buttons/FutureButton/FutureButton.tsx
src/components/Buttons/FutureButton/FutureButtonStyle.module.scss
src/components/Spinner/Spinner.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Reduce-glow-on-primary-buttons-db9d75237a604b00aab1cd5ee4baae39)
-----
Feature
- Button glows were too big
- We had an overly complex hover animation
- No "active" button state (mouse down)
- Font size was 16 (should be 14)
- Spinner was too big
- Shrunk button glows
- Reduced complexity of the hover animation
- Added an "active" state
- Shrunk font to 14px
- Shrunk spinner to fit button better
Also did some solid refactoring of the FutureButton component.

feat: Adjust button glows

---

src/components/Confirmation/Confirmation.module.scss
src/components/Confirmation/Confirmation.tsx
src/containers/PageContainer/PageContainer.constants.ts
src/containers/PageContainer/elements/Header/Header.tsx
src/containers/PageContainer/elements/Header/_header.scss
src/containers/PageContainer/elements/Header/elements/ConnectWalletButton/ConnectWalletButton.tsx
src/containers/PageContainer/elements/Header/elements/ConnectWalletButton/hooks/useConnectWalletButtonData.ts
src/containers/flows/MintDropNFT/MintDropNFTWizard.module.scss
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintNewNFT/MintNewNFT.module.scss
src/containers/flows/MintNewNFT/sections/TokenInformation.tsx
src/containers/lists/BidList/BidList.module.scss
src/containers/prompts/ConnectWalletPrompt/ConnectWalletPrompt.tsx
src/containers/staking/DepositTable/DepositTableCard.module.scss
src/containers/staking/DepositTable/DepositTableCard.tsx
src/containers/staking/StakePoolTable/StakePoolTableCard.module.scss
src/containers/staking/StakePoolTable/StakePoolTableCard.tsx
src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
src/containers/staking/flows/ClaimFlow/ClaimFlow.module.scss
src/containers/staking/flows/StakeFlow/StakeFlow.module.scss
src/pages/Profile/Profile.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=0c852e639aae46f6b27827f160dd8c89)
-----
Currently unable to action the following: 
1. View Bids on mobile 
2. Profile Disconnect Button on mobile
3. Center Profile Disconnect Text when disconnected on mobile
4. Connect Wallet Prompt on mobile
5. Claim Flow on Mobile
6. Stake Flow on Mobile
7. Pools Table Stake Button on mobile
8. My Deposits Three Dot menu on mobile
9. Mint/Request To Mint on mobile
10. Mint Drop NFT on mobile
Now able to action the above.

feat: Improve mobile usability (Dom)

---

src/assets/user_icon.svg
src/components/Tooltip/Tooltip.module.scss
src/lib/network.ts
src/lib/utils/domains.ts
src/pages/Profile/Profile.constants.tsx
src/pages/Profile/Profile.module.scss
src/pages/Profile/Profile.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Implement-Design-20474c2cc6da410a9712678656571fd1)
-----
Feature
Eth address component in Profile was updated in a newer Figma doc, so the old one was out of date.
Matched the Eth address component in Profile to match Figma.
Looms in Notion card.

feat: Improved profile address

---

src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx

bug: prevent user bidding on own domain - disable bid button

---

src/components/Dropdowns/OptionDropdown/OptionDropdown.tsx
src/components/NFTMedia/config.ts
src/components/NFTMedia/index.tsx
src/containers/flows/MintDropNFT/index.tsx
src/containers/other/NFTView/NFTView.constants.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/assets/image.svg
src/containers/other/NFTView/assets/video.svg
src/containers/other/NFTView/elements/NFT/NFT.module.scss
src/containers/other/NFTView/elements/NFT/NFT.tsx
src/containers/other/NFTView/hooks/index.ts
src/containers/other/NFTView/hooks/useNftData.ts
src/containers/other/NFTView/hooks/useNftMediaAsset.ts

[Associated Notion Card](https://www.notion.so/zerotech/Add-option-for-downloading-preview-image-or-full-image-for-Twitter-d7e5b4e18b274b97aa10b21d358d9be7)
-----

Add option for downloading preview image or full image  for Twitter

---

src/components/Preview/Preview.module.scss
src/components/Preview/Preview.tsx
src/components/Tables/GenericTable/GenericTable.module.scss
src/containers/PageContainer/PageContainer.module.scss
src/containers/PageContainer/elements/Actions/Actions.tsx
src/containers/PageContainer/elements/Header/_header.scss
src/containers/PageContainer/elements/Touchbar/Touchbar.module.scss
src/containers/PageContainer/elements/Touchbar/Touchbar.tsx
src/containers/Tables/SubdomainTable/SubdomainTableCard.module.scss
src/containers/other/NFTView/NFTView.module.scss
src/containers/other/NFTView/elements/NFT/NFT.module.scss
src/pages/ZNS/ZNS.module.scss
src/pages/ZNS/ZNS.tsx
src/styles/main.scss

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=285f0574aca045fa911982f07245f593)
-----

Check and Update Responsiveness UI 

---

package.json
src/components/Banners/MintDropNFTBanner/MintDropNFTBanner.tsx
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/Raffle/RaffleRegistration/RaffleRegistration.tsx
src/containers/flows/Raffle/RaffleRegistration/index.tsx
src/containers/flows/Raffle/index.tsx
src/pages/ZNS/ZNS.tsx

**Associated Notion Card**
- [Mintlist Sign Up dApp & zNS Banner - AIR WILD Season Two](https://www.notion.so/zerotech/Mintlist-Sign-Up-dApp-zNS-Banner-AIR-WILD-Season-Two-b212f3d7c0754fa79cdbeb62dd1af9ed)
- [Add Genesis check to Mintlist Signup](https://www.notion.so/zerotech/Add-Genesis-check-to-Mintlist-Signup-229e73c46ff948309de394387d49151c)
-----

Air Wild Season 2 - Mintlist Signup

---

package-lock.json
package.json
src/constants/daos.ts

[Associated Notion Card](https://www.notion.so/zerotech/Add-Wilder-Beasts-DAO-6d8022ba806a46888b21e44d781f9e3d)
-----
There was no Wilder Beasts DAO
Added the Wilder Beasts DAO to the DAO list

feat: Add Wilder Beasts DAO

---

package-lock.json
package.json
src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/Approval/Approval.tsx
src/containers/flows/MintDropNFT/steps/Finished/Finished.tsx
src/containers/flows/MintDropNFT/steps/Info/Info.tsx
src/containers/flows/MintDropNFT/steps/InsufficientFunds/InsufficientFunds.tsx
src/containers/flows/MintDropNFT/steps/Loading/Loading.tsx
src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/Raffle/WaitlistRegistration/WaitlistRegistration.tsx
src/containers/flows/Raffle/index.tsx
src/lib/hooks/useMint.ts
src/pages/ZNS/ZNS.tsx

[Air Wild Season 2](https://www.notion.so/zerotech/Mint-List-Community-Sale-b4b1974f06b042bf9a0d167ddc84cc7a)
-----

feat(mint-drop): banner changes to support kicks s2 drop

---

package-lock.json
package.json
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/Raffle/index.tsx
src/lib/hooks/sdk/useZSaleSdk.tsx

[Air Wild Season 2](https://www.notion.so/zerotech/Air-Wild-Season-2-656dacdd5ad340b09e4c5ce66b650641)
-----

feat(mint-drop): sdk integration changes to support kicks s2 drop

---

package-lock.json
package.json
src/containers/flows/MintDropNFT/index.tsx
src/containers/flows/MintDropNFT/labels.tsx
src/containers/flows/MintDropNFT/steps/SelectAmount/SelectAmount.tsx
src/containers/flows/Raffle/index.tsx
src/lib/hooks/sdk/useZSaleSdk.tsx

feat(mint-drop): update banner with sample sale times

---

package.json
src/components/Artwork/Artwork.tsx
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=e75e5440376945138e48a4225ce432fb)
-----

fix: increase character limit and width of container to resolve truncated domain issue

---

package.json
src/pages/ZNS/ZNS.tsx

[Air Wild Season 2](https://www.notion.so/zerotech/Air-Wild-Season-2-656dacdd5ad340b09e4c5ce66b650641)
-----

feat(mint-drop): hide the banner

---

.gitignore

[Associated Notion Card](https://www.notion.so/zerotech/Add-Intellij-config-folder-to-gitignore-eeb5eadab5184f3c8ed604d3eba96d55)
-----
Intellij/Webstorm config folders weren't in gitignore.
Intellij/Webstorm config folders are now in gitignore.

chore: add Intellij configs to gitignore

---

package.json
src/containers/flows/MakeABid/MakeABid.constants.tsx
src/containers/flows/MakeABid/MakeABid.tsx
src/containers/flows/MakeABid/components/Details/Details.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Loading-Bid-Data-infinite-loading-loop-error-69cf72ef21ce46bab8101a583887e2f0)
-----
Bugfix
- Bid modal was getting stuck in an infinite loop if the connected wallet had 0 balance. 
- Bid modal would not start from the start if the connect wallet changed while the modal was open, meaning a user could accidentally place a bid without approving zAuction.
- The text while loading the "Place Bid" step in the modal is "Loading Bid Data", when it should be "Loading Domain Data"
- Bid modal now progresses with an error message if the user has 0 WILD. 
- The flow will also start from the start on wallet change.
- Modal loading text now says "Loading Domain Data"

fix: bid modal not loading, bid modal not restarting on wallet change

---

src/components/NFTMedia/index.tsx

-----
Preview images would sometimes load from IPFS when navigating between domains.
Ensure preview images (and all images) load correctly from Cloudinary.

fix(nft-media): more reliable image loading

---

src/components/Cards/ImageCard/ImageCard.module.scss
src/components/Confirmation/Confirmation.module.scss
src/components/NFTMedia/NFTMedia.module.scss
src/components/StatsWidget/StatsWidget.module.scss
src/components/Wizard/Wizard.tsx
src/containers/flows/AcceptBid/AcceptBid.constants.tsx
src/containers/flows/AcceptBid/AcceptBid.tsx
src/containers/flows/AcceptBid/hooks/useAcceptBid.test.tsx
src/containers/flows/AcceptBid/hooks/useAcceptBid.ts
src/containers/flows/BuyNow/Steps/Details.module.scss
src/containers/flows/MakeABid/MakeABid.constants.tsx
src/containers/flows/SetBuyNow/SetBuyNow.tsx
src/containers/other/NFTView/elements/DomainSettings/elements/DocumentSettingsModal/_domain-settings-modal.scss
src/containers/other/NFTView/elements/DomainSettings/elements/DomainSettingsBody/hooks/useDomainSettingsBodyData.tsx
src/containers/staking/DepositTable/DepositTableCard.module.scss
src/containers/staking/DepositTable/DepositTableCard.tsx
src/containers/staking/DepositTable/DepositTableRow.module.scss
src/containers/staking/DepositTable/DepositTableRow.tsx
src/containers/staking/StakePoolTable/StakePoolTableRow.module.scss
src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
src/containers/staking/flows/StakeFlow/StakeFlow.tsx
src/containers/staking/flows/StakeFlow/steps/Approve/Approve.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=b82bd575da3e48b29a0753ab410e4549)
-----
Mixture of bugfixes/hotfixes and design changes
Place a Bid - No ‘$’ Before USD value
Buy Now - Sub title message should not display when processing transaction
Possible to accept an already ‘accepted’ bid
Staking flow shows two headers
Connect Wallet Button is too big in desktop screen
Update useAcceptBid tests and resolve failing tests
Staking Modal should not have a header
Stat card in NFT view should be same height as other cards
Domain settings - cross icon out of position
Domain settings - domain bidding and grid view by default should be toggled by default
The above issues have been resolved.

Fix: 0.15.0 (Reskin) Bundle of Bugs/Updates

---

src/containers/other/NFTView/elements/DomainSettings/hooks/useDomainSettingsHandlers.tsx

fix: parsing domain metadata

---

package-lock.json
src/components/Cards/ImageCard/ImageCard.module.scss
src/components/Confirmation/Confirmation.module.scss
src/components/NFTMedia/NFTMedia.module.scss
src/components/StatsWidget/StatsWidget.module.scss
src/components/Tables/GenericTable/GenericTable.tsx
src/components/Wizard/Wizard.tsx
src/containers/flows/AcceptBid/AcceptBid.constants.tsx
src/containers/flows/AcceptBid/AcceptBid.tsx
src/containers/flows/AcceptBid/hooks/useAcceptBid.test.tsx
src/containers/flows/AcceptBid/hooks/useAcceptBid.ts
src/containers/flows/BuyNow/Steps/Details.module.scss
src/containers/flows/MakeABid/MakeABid.constants.tsx
src/containers/flows/MintDropNFT/MintDropNFTWizard.tsx
src/containers/flows/SetBuyNow/SetBuyNow.tsx
src/containers/other/NFTView/elements/DomainSettings/elements/DocumentSettingsModal/_domain-settings-modal.scss
src/containers/other/NFTView/elements/DomainSettings/elements/DomainSettingsBody/hooks/useDomainSettingsBodyData.tsx
src/containers/other/NFTView/elements/DomainSettings/hooks/useDomainSettingsHandlers.tsx
src/containers/staking/DepositTable/DepositTableCard.module.scss
src/containers/staking/DepositTable/DepositTableCard.tsx
src/containers/staking/DepositTable/DepositTableRow.module.scss
src/containers/staking/DepositTable/DepositTableRow.tsx
src/containers/staking/StakePoolTable/StakePoolTableRow.module.scss
src/containers/staking/StakePoolTable/StakePoolTableRow.tsx
src/containers/staking/flows/StakeFlow/StakeFlow.tsx
src/lib/hooks/useInfiniteScroll.tsx
src/lib/hooks/useInterval.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Merge-develop-zero-live-93bfae5e6e674733a50df531ec8b0bbb)

chore: merge develop->zero.live

---

src/components/SideBar/SideBar.module.scss
src/components/SideBar/SideBar.tsx
src/constants/domains.ts

[Associated Notion Card](https://www.notion.so/zerotech/Fix-incorrect-logo-in-top-left-corner-e331228c996144c6b25127f028f8437c)

feat(side-bar): dynamic side bar logo

---

package.json
src/components/Cards/ImageCard/ImageCard.module.scss
src/components/Tables/GenericTable/GenericTable.tsx

Bring hotfix from `master to `zero-live`

chore: update zero-live

---

package.json
src/containers/other/NFTView/hooks/useAsset.ts
src/containers/other/NFTView/hooks/useNftData.ts

[Associated Notion Card](https://www.notion.so/zerotech/Download-PFP-downloading-video-instead-of-PFP-Beasts-bc9128cf245c473684d52cfa0fded125)
-----
Bugfix

fix: PFP download downloading video

---

src/components/Cards/ImageCard/ImageCard.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/Fix-spinner-in-background-of-transparent-images-in-ImageCard-c94beb4d6e544f32bbf4769d3db5ca08)
-----
Bugfix

fix: loading spinner below transparent image

---

src/components/Cards/ImageCard/ImageCard.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/Fix-spinner-in-background-of-transparent-images-in-ImageCard-c94beb4d6e544f32bbf4769d3db5ca08)
-----
Bugfix

fix: loading spinner below transparent image 

---

src/components/ZNALink/ZNALink.tsx

[Associated Notion Card](https://www.notion.so/zerotech/zNA-Navigation-Bug-fb5ad2dc75224d0a85e3f5bfa8495132)
-----
Bugfix
As per Loom in Notion card.
As per Loom in Notion card.

fix: zNA link segments linking to incorrect location

---

src/components/Chiclet/Chiclet.module.scss
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/DAO/pages/DAOPage/Proposals/Proposals.tsx
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTable.module.scss
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTable.tsx
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTableCard.tsx
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTableRow.module.scss
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTableRow.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Table-Feedback-16bdb553718441368d97637a98a40394)
-----
BugFix
1. Proposals table refreshed whenever the `Proposals` tab clicked
2. Wrong font size, color, margin, ..etc in Proposals Table

 fix: table iteration feedback

---

src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/ProposalDetail.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/Vote.module.scss
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/Vote.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/VoteButtons.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/VoteModal.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/useVoteData.ts

[Associated Notion Card](https://www.notion.so/zerotech/Implement-UI-ec0029ca125d4fc3af7d8507cf9ba43f)
-----
Feature
There was no way to vote on proposals.
Added the footer and voting modal per Figma.

feat(dao): voting on proposals

---

src/components/MarkDown/MarkDown.module.scss
src/components/MarkDown/MarkDownViewer.tsx
src/components/Tables/GenericTable/GenericTable.tsx
src/constants/daos.ts
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/ProposalDetail.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/Vote.module.scss
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/Vote.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteAttributes/VoteAttributes.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteBar/VoteBar.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteHistories/VoteHistories.module.scss
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteHistories/VoteHistories.tsx
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTable.module.scss
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTableRow.module.scss
src/containers/DAO/pages/DAOPage/Proposals/PropsalsTable/ProposalsTableRow.tsx
src/containers/DAO/pages/DAOPage/hooks/useProposals.ts

[Associated Notion Card](https://www.notion.so/zerotech/Implement-UI-ec0029ca125d4fc3af7d8507cf9ba43f)
-----
Feature / Bugfix

fix: proposal feedback

---

src/components/Tables/GenericTable/GenericTable.tsx
src/containers/PageContainer/index.tsx
src/containers/Tables/SubdomainTable/SubdomainTable.tsx
src/containers/Tables/SubdomainTable/hooks/useSubdomainData.ts
src/containers/Tables/SubdomainTable/hooks/useSubdomainTableData.ts
src/lib/hooks/useZnsDomain.tsx
src/pages/ZNS/ZNS.tsx

- Memoise some components
- Combine state updates in CurrentDomainProvider which were previously split by async logic
- Re-enable stat cards

feat: improve loading efficiency of Subdomain Table

---

src/pages/ZNS/ZNS.tsx

feat(zns): show payment token symbol in stats

---

package-lock.json
package.json
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx

fix(subdomain-table-card): avoid showing spinner when data is unavailable

---

package-lock.json
package.json

Release 0.17.3

---

package-lock.json
package.json
src/components/Tables/GenericTable/GenericTable.tsx
src/constants/daos.ts
src/containers/DAO/pages/DAOPage/Assets/Assets.tsx
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.helpers.ts
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.tsx
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.type.ts
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTableCard.tsx
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTableRow.module.scss
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTableRow.tsx
src/containers/DAO/pages/DAOPage/Proposals/CreateProposal/CreateProposalForm.tsx
src/containers/DAO/pages/DAOPage/Proposals/CreateProposal/hooks/useCreateProposalForm.ts
src/containers/DAO/pages/DAOPage/hooks/useAssets.ts

[Associated Notion Card](https://www.notion.so/zerotech/DAO-app-speed-improvements-17b89727529d4243a5ccf64856704219)
-----
Feature
As described in Notion - DAO loading was very slow.
Faster DAO loading, due to deferring IPFS metadata fetch to asset table rows.

feat(daos): improve daos loading time

---

src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/ProposalAttributes/ProposalAttributes.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/VoteAction.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Handle-delayed-voting-bfaf57923c814128a86ca9b56ed762bd)
-----
Feature
Voting delays were not implemented - instead the UI would let users go through the voting process, which would end in an error.
- Shows a timer if the proposal voting hasn't started.
- Shows "Voting Starts" before voting has started, "Voting Started" after.
- (extra) Changed "Voting System" attribute so it's not hard-coded.

feat: handle delayed voting

---

src/lib/addresses.ts
src/lib/dao/providers/ZdaoSdkProvider.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Use-zDAO-contract-on-Rinkeby-3becb3f07e55447caa2dc5c7d6597273)
-----
Feature
We were using `createZDaoFromParams` (hard-coding) rather than getting DAO index through the contract.
We are getting DAO index through the zDAO contract.

feat: use zDAO contract on Rinkeby

---

package.json
src/components/SideBar/SideBar.utils.ts
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/ProposalAttributes/ProposalAttributes.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/Vote/VoteAction.tsx
src/lib/addresses.ts
src/lib/dao/providers/ZdaoSdkProvider.tsx

- Handle delayed voting
- Use zDAO contract on Rinkeby
- Fix Wilder logo resetting on app change (in WWMM build)

Release 0.18.0

---

package.json
src/lib/metadata.ts

- Hotfix for metadata not loading on Moto NFTs

Release 0.18.1

---

src/containers/DAO/pages/DAOPage/Transactions/Transactions.helpers.tsx
src/containers/DAO/pages/DAOPage/Transactions/components/History/History.helpers.ts

[Associated Notion Card](https://www.notion.so/zerotech/Fix-DAO-Transactions-bugs-bd01bc41883a45509652634cfd873852)
-----
Fix
- Transaction sorting was weird (because "is today" logic was broken).
- Transaction History items were using the "to" address instead of "from".
- Transaction sorting is now correct.
- Transaction History items now link to the correct address ("from").

fix: DAO Transaction history issues

---

package.json
src/containers/DAO/pages/DAOPage/Transactions/Transactions.helpers.tsx
src/containers/DAO/pages/DAOPage/Transactions/components/History/History.helpers.ts

[Associated Notion Card](https://www.notion.so/zerotech/0-18-2-e26e0ac3339d462abc8b9bee639763ca)
- Fixes issues with DAO transaction history

Release 0.18.2

---

.env.sample
src/constants/daos.ts
src/lib/addresses.ts
src/lib/dao/providers/ZdaoSdkProvider.tsx
src/lib/hooks/sdk/useZSaleSdk.tsx
src/lib/network.ts
src/lib/providers/ZnsSdkProvider.tsx

build: add support to goerli test network

---

package-lock.json
package.json
src/lib/hooks/sdk/useZSaleSdk.tsx

chore: bump package version to v0.18.5

---

package-lock.json
package.json
src/containers/DAO/pages/DAOPage/Proposals/Proposals.helpers.ts

Merging latest `develop` branch into `master` - updating to v0.19.0 which contains zdao-sdk version bump and bug fixies.
Merge includes:
- PR 668

chore: master <- develop merge v0.19.0

---

package-lock.json
package.json

[Associated Notion Card](https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-57)
-----
- Bugfix
Error resolved by bumping zdao-sdk version. CPT made the required changes.

fix: resolve network error thrown due to snapshot server updates

---

package-lock.json
package.json
src/containers/DAO/pages/DAOPage/Proposals/Proposals.helpers.ts

[Associated Notion Card](https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-57&quickFilter=15)
-----
- merge develop to master (chore)
Master branch not up to date with latest additions to Develop branch.
Master branch is up to date - inc. version numbers for zdao-sdk and this package.

chore: master <- develop merge v0.19.1

---

package.json
src/pages/ZNS/ZNS.tsx

feat(gens-drop): hide the banner

---

src/containers/DAO/pages/DAOList/DAOList.tsx
src/containers/DAO/pages/DAOList/DAOTable/DAOTableCard.tsx
src/containers/DAO/pages/DAOList/DAOTable/DAOTableRow.tsx
src/containers/DAO/pages/DAOList/TotalProvider.tsx
src/containers/DAO/pages/DAOPage/Assets/Assets.tsx
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.module.scss
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.tsx
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteHistories/VoteHistories.tsx
src/containers/DAO/pages/DAOPage/hooks/useAssets.ts

[Associated Notion Card](https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-142)
-----
- Bugfix
List assets was throwing errors causing loading to hang for totals and assets table on DAO dApp.
Replaced list all assets with list coins.
Refactored some UI to reflect the changes.
Loom - https://www.loom.com/share/12d3df6074384719b48a1dd164aa08b2

fix: handle broken listAssets and listVotes functions

---

src/containers/other/NFTView/elements/Stats/Stats.tsx
src/pages/ZNS/ZNS.tsx

feat: remove metrics

---

package-lock.json
package.json
src/containers/DAO/pages/DAOList/DAOList.tsx
src/containers/DAO/pages/DAOList/DAOTable/DAOTableCard.tsx
src/containers/DAO/pages/DAOList/DAOTable/DAOTableRow.tsx
src/containers/DAO/pages/DAOList/TotalProvider.tsx
src/containers/DAO/pages/DAOPage/Assets/Assets.tsx
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.module.scss
src/containers/DAO/pages/DAOPage/Assets/AssetsTable/AssetsTable.tsx
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/VoteHistories/VoteHistories.tsx
src/containers/DAO/pages/DAOPage/hooks/useAssets.ts
src/containers/other/NFTView/elements/Stats/Stats.tsx
src/pages/ZNS/ZNS.tsx

- chore: bump version 0.20.3 -> 0.20.4
- updated package-lock.json

chore: bump version (`0.20.3`) -> (`0.20.4`)

---

src/containers/other/NFTView/NFTView.constants.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/hooks/useNftMediaAsset.ts
src/lib/metadata.ts
src/lib/types.ts

[Associated Notion Card](https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-168)
-----
- feature
Unable to download multiple PFP images
Able to download multiple PFP images
https://user-images.githubusercontent.com/39112648/234733040-ffeae441-87e6-4b5e-817b-445da8b97d39.mov

feat: add additional pfp static image download options

---

package-lock.json
package.json
src/containers/other/NFTView/NFTView.constants.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/hooks/useNftMediaAsset.ts
src/lib/metadata.ts
src/lib/types.ts

- merge `develop` branch into `master` branch (add additional pfp static image download options)
- bump `zNS-dApp` version (`0.20.4`) -> (`0.21.0`)

chore: bump version (`0.20.4`) -> (`0.21.0`) 

---

package-lock.json
package.json

- Bumps `@zero-tech/zapp-staking` to `0.6.0`

chore: bump zapp-staking

---

package-lock.json
package.json
src/components/ConnectToWallet/ConnectToWallet.tsx
src/constants/domains.ts
src/styles/main.scss

- Set Metamask as first option in wallet modal
- Hide DAO connect wallet button
- Add hardcoded DAOs
- Bump `@zero-tech/zapp-daos` version

feat: DAO fixes
