zer0-os/zNS-dapp

src/components/topbar/topbar/topbar-global.tsx
src/lib/useDomainStore.ts

Added code to hide the mint button when a user wouldn't be able to mint a domain from their current page.
Ideally the button would just be greyed out but there is no ability to 'disable' a 'FutureButton' right now.

Disables (hides) mint button when it cannot be used

---

src/styles/main.css

For browsers which don't support the `backdrop-filter` CSS property:
- Elements which apply the class `.blur` will have more opaque backgrounds
- Overlay background is more opaque

Better support for browsers which don't support the 'backdrop-filter' CSS property

---

src/components/Tables/DomainTable/HighestBid.tsx
src/components/Tables/DomainTable/NumBids.tsx
src/containers/NFTView/NFTView.tsx

Got given some feedback that some numbers weren't formatted to the user's locale, i.e. 1000.00 as 1,000.00, or 1.000,00, etc. I had a scan over all the places we're rendering numbers, and it looks like `NumBids.tsx` and `HighestBid.tsx` were the only places not converting to a locale string.
Also removed a line where a WILD value was being rounded to 2dp (history items in `NFTView.tsx`).

Numbers to locale strings

---

src/components/Profile/Profile.tsx
src/components/Tables/DomainTable/DomainTable.tsx
src/containers/MakeABid/MakeABid.tsx
src/containers/NFTView/NFTView.tsx
src/pages/ZNS/ZNS.tsx

**Problem 1**
Problem: Used to be able to bid on your own domains by opening the bid modal with a different wallet connected, then switch to your main wallet.
Solution: Flow already resets on wallet change - added a check on the first step of the flow to disable the input/continue button when `connected wallet ID === domain owner ID`.
**Problem 2**
Problem: Should not be able to have bid or profile modals open without a wallet connected. With modals open, disconnecting wallet would not close them, which could lead to some functionality crashing.
Solution: Added checks for connected account - if not connected close the bid or profile modal (if open). Also made the bid and profile modals render blank if no `userId` is supplied - not sure if this is the greatest solution.
**Problem 3** …

Fixes for problems that arise when switching/disconnecting wallets

---

src/components/Tables/RequestTable/components/RequestActions.tsx

**Problem**
Request cards (in the grid view of the "Offers" table in Profile) were showing `WILD` by default, but they should say `LOOT`.
**Solution**
I found that there is a `stakeCurrency` string inside the request object, so I just put `stakeCurrency` where `WILD` was and it solved it.

Request cards show proper currency, rather than defaulting to WILD

---

src/components/Tables/DomainTable/DomainTable.tsx
src/components/Tables/DomainTable/components/ViewBids.tsx

**Problem**
In the process of ironing out the Domain Tables, we dropped the 'View Bids' button from the owned domains table in the Profile modal. This needs to be re-added.
**Solution**
Made a `ViewBids` component, which renders a `FutureButton` with some added validation and API calls. `ViewBids` grabs bid data from API (this will be cached by library that handles this, so it won't add any additional network requirements). If it finds bids, then it makes itself clickable and triggers the passed in click handler. If it finds no bids, then it remains disabled.

Add missing view/accept bid flow to owned domains table

---

src/components/Cards/PreviewCard/PreviewCard.module.css
src/containers/NFTView/NFTView.module.css
src/containers/NFTView/NFTView.tsx
src/styles/main.css

The galaxy background in NFT view now fades in, which is especially important on slower networks

NFT view galaxy background should fade

---

src/components/Cards/PreviewCard/PreviewCard.module.css
src/components/Cards/PreviewCard/PreviewCard.tsx
src/components/Cards/PreviewCard/index.tsx
src/components/Tables/RequestTable/components/RequestActions.tsx
src/pages/ZNS/ZNS.tsx

Better Preview Card animations

---

src/containers/MakeABid/MakeABid.tsx

Bid Modal Tweaks

---

src/components/ConnectToWallet/ConnectToWallet.tsx
src/lib/hooks/provider-hooks.ts

This error its generated by the lost of authorization to connect, page shouldnt try to reconnect if user isnt authorized yet
Also Metamask may get stuck with requestAccounts promise if user close login overlay, for this, page will try to detect if its stuck and reload, or ask user to reload with a timeout if promise cant resolve. Other DAPPS like opensea / pancakewap / hypertext, displays an error message and ask user to reload
Flow:
User has metamask extension? works OK
User has brave and load crypto wallets at start enabled? works OK
User has brave and not enabled crypto wallets or metamask extension?
-First pop up message asking for extension or crypto wallets to start and reload
-Second when user has the provider available pop ups log in overlay
-Last, if log in sucess, then reloads …

Metamask connecting/reconnecting stuck forever fix

---

src/lib/hooks/useZnsDomain.tsx

If the domain keeps null ( without fetched data ) after some time then its invalid and must redirect user to home

If domain URL its invalid get user back to home after 2 seconds

---

src/components/Tables/DomainTable/DomainTable.tsx
src/components/Tables/DomainTable/components/NumBids.tsx
src/components/Tables/DomainTable/components/ViewBids.tsx
src/containers/OwnedDomainsTable/OwnedDomainsTable.tsx
src/lib/providers/BidProvider.tsx

Changed filter to be optional, and setted from domainTable component props.
Bid history on nftview will display and use the data for all bids, including the ones from the current owner of the domain.
My domains tab in profile, will show only the bids from other users

Bid history should show your own bids

---

src/containers/NFTView/NFTView.tsx

Steps to reproduce:
Disconnect wallet
Navigate to NFT View of any domain
Hit "Make A Bid"
A blank semi-transparent black overlay will mask the UI

FIX Blank overlay if user press "make a bid" button disconnected

---

src/components/Buttons/IconButton/IconButton.tsx
src/components/NavBars/TitleBar/TitleBar.module.css
src/components/Overlay/Overlay.module.css
src/components/Overlay/Overlay.tsx
src/containers/NFTView/NFTView.module.css
src/pages/ZNS/ZNS.tsx
src/styles/main.css

A few high priority tweaks necessary for progressing the mobile experience. Cards from zer0  attached.
Loom explanation of problems and fixes
https://www.loom.com/share/961a4722bee44b23bc12762c345896d6
______________
**Fixes**
_Problem 1_
Border radius not applying to the black background for the NFT section in NFT view
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/d9a42ec6-233b-4960-8761-1363116a5923
_Solution_
Apply border radius to black background
______________
_Problem 2_
UX was confusing navigating between domains because navigating domains would keep you at the bottom of the list, rather than scrolling up to the preview of the NFT you just clicked
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/b31292c8-58b1-4e17-a6c9-a3c4a969 …

Post-release mobile tweaks

---

src/components/Artwork/Artwork.module.css
src/components/Cards/PreviewCard/PreviewCard.tsx
src/components/Image/Image.module.css
src/components/Image/Image.tsx
src/containers/MakeABid/MakeABid.tsx
src/containers/NFTView/NFTView.tsx
src/containers/Request/Request.tsx
src/containers/TransferOwnership/TransferOwnership.tsx

**zer0 task:** https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/0177518e-9583-408b-be96-6eca6a2209f6
**Loom:** https://www.loom.com/share/4d2882f237f04f8d8ea34bc3bb5a85fa
_______________
Previously, Image components would just play videos by default with sound on. Unfortunately (for devs, fortunately for users) browsers are pretty strict on autoplaying videos with audio, especially on mobile devices. Instead of coming up with a hacky solution, for now it will just be best to show the default video controls.
`Image.tsx` was previously failing to load videos nicely on iOS - it would load them into an `<img>` which obviously was preventing controls from appearing. And, since audio is disabled by default in iOS, it meant you couldn't turn audio on.
1.  Rewrote …

Updates to Image component to allow for video controls (including bugfixes for iOS)

---

src/components/Tables/DomainTable/components/ViewBids.tsx

Changed as eth fish said in his video, displays "no bids" if there are no bids available to accept ( code filter user own bids, so it will display active buttons when another user makes bids )

Changed my domains inactive buttons to display text instead

---

public/index.html

Switches Fathom Integration to force hash based routing instead of enabling auto-detection. This will allow us to see visits and users for specific namespaces on Fathom.

Switch Fathom from Auto to Hash

---

src/components/Banners/CountdownBanner/CountdownBanner.module.css
src/components/Banners/CountdownBanner/CountdownBanner.tsx
src/components/Banners/CountdownBanner/countdown.json
src/containers/Tables/SubdomainTable/SubdomainTable.tsx
src/pages/ZNS/ZNS.tsx

Set up a nicer auction countdown timer. Still not the ideal solution we're after, but a much nicer iteration.
**Changes**
Added pre and post messaging - "auction starting in x", "auction ended". You can set an amount of time for these messages to be visible for, so auction start countdown starts 12 hours before the auction, and the auction end message disappears after 3 hours.
Set up values for next drop - may need changing

Better auction countdown banner

---

src/components/Inputs/TextInput/TextInput.tsx
src/containers/MintNewNFT/MintNewNFT.tsx
src/containers/MintNewNFT/sections/TokenInformation.tsx
src/lib/providers/MintProvider.tsx
src/lib/providers/StakingRequestProvider.tsx

All domain names need to be lower case. This PR adds validation to prevent transactions happening if someone inputs a lowercase domain in the Mint flow.
Validation:
1. In the Information section of the Mint flow (i.e. page 1) - you can't continue with the flow if the domain has an uppercase character.
2. A check in the final submit method of the Mint flow, just in case the first bit of validation failed, or in case someone is trying to circumvent the first step.
3. An extra check in the Mint & Staking providers - this one should never be hit, but probably wise to have it in there.
Note:
In the requirements, it said uppercase characters should be automatically converted to lowercase as they're typed out, but that made the input feel broken. Instead, the dapp renders an error label below …

Client-side enforcement of lowercase domain names in Mint flow

---

src/components/Cards/PreviewCard/PreviewCard.module.css
src/components/Overlay/Overlay.module.css

**Summary**: 
Overlay backdrop isn't taking up the full screen
The issue is due to the following polyfill styles in `main.css`
```
/*
*
* Polyfills
*
*/
@supports not (
(-webkit-backdrop-filter: blur(20em)) or (backdrop-filter: blur(2em))
) {
.blur {
background: rgba(78, 0, 132, 0.4) !important;
}
.overlay {
background: rgba(0, 0, 0, 0.4) !important;
}
}
```
In firefox the above polyfill kicks in and causes the overlay to have a different opacity due to `!important`.
**Task URL**:
https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/3f2927e7-4103-49ce-8efb-745b78a31aed

fix(overlay): issue with background visibility for overlay in firefox

---

src/components/NFTMedia/index.tsx
src/lib/metadata.ts

What this is
We're switching the metadata of our NFTs slightly. Images will now be stored at ipfs://[hash] instead of https://ipfs.fleek.co/ipfs/[hash]. We need to handle both of these cases in the dapp.
Solution
Added a case to our "get hash from URL" method in the NFTMedia container which handles ipfs://[hash] URLs.

Handle new NFT image URLs

---

src/containers/other/NFTView/NFTView.module.scss
src/containers/other/NFTView/NFTView.tsx

Fixed a bug where the download button would always download the asset as a png

Fix for incorrect file on asset download

---

package.json
src/containers/Tables/SubdomainTable/SubdomainTable.tsx

**Problem**
Navigating to a domain which you have already loaded would make the subdomain table fail to load. 
**Solution**
Switched current domain vs loading domain tracking to a ref, rather than a state object.

Fix navigation bug

---

src/components/Tables/DomainTable/DomainTable.module.scss
src/components/Tables/RequestTable/RequestTable.module.scss

https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/e0514249-f173-47b1-966d-f8f7e6ff00ed
-----
Buttons on the list view have a grow animation when you hover it.
Disable that geow animation in the list view.

Disable button grow on list tables

---

package.json
src/containers/flows/MintWheels/index.tsx
src/containers/flows/MintWheels/labels.tsx

If the countdown ends but the contract hasn't started (for whatever reason), the banner should refetch until the contract is live

Wait for public sale to start before refetching

---

src/containers/other/NFTView/NFTView.module.scss

[Link to Card](https://www.notion.so/rational-nomads/Moved-From-Zero-BUG-Fix-Style-of-Attributes-label-on-NFT-View-c9b28933b4824b909686701183ee5bed)
-----
The title of attributes container was all uppercase.
Changed the title to Capitalize to match Figma design

Update attribute's title to match Figma design

---

src/lib/utils/number.spec.ts
src/lib/utils/number.ts

Link to associated zer0 card:  [Notion Card](https://www.notion.so/rational-nomads/67a5d1b61d4146f491d5996a17b14a81?v=4f04ed31a23340bfbbdc5560502bc429&p=4d62ccf715fc40e4a0ca203edea1ced1)
-----
Existing format number util doesn't allow us to pass a desired amount of decimal places to display in the UI on a value.
New formatByDecimalPlace util allows us to add a desired amount of decimal places to display. Fully tested.
The reason for this ticket was due to displaying wild percentage change in ui. This PR will need to be merged first.
[Loom](https://www.loom.com/share/65afb1e2c2a1429096a6ff65d5535cd5)

Add flexible formatByDecimalPlace util function and tests

---

src/components/Tables/DomainTable/DomainTable.tsx
src/components/Tables/DomainTable/components/NFTCardActions.module.scss
src/components/Tables/DomainTable/components/NFTCardActions.tsx
src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.tsx
src/pages/ZNS/ZNS.tsx

Link to associated zer0 card:  [Zero Card on Notion](https://www.notion.so/Add-a-View-Bids-button-to-NFT-Grid-View-in-Owned-Domains-Table-fdf5ce5f3afb4e5ca1bcc624ef5fafd1)
-----
NFT card on the owned domain table does not currently have a cta to view bids when in grid view.
View bids cta has been added to NFT card on the owned domain table when in grid view.

Add a 'View Bids' button to NFT Grid View in Owned Domains Table

---

package-lock.json
src/containers/staking/Deposits/Deposits.tsx

[Associated Notion Card](https://www.notion.so/Handle-infinite-loading-staked-balance-issue-2f86268078ee4cdda574f475b85272a4)
-----
Bugfix
"Total Stake (USD)" widget would load infinitely if the user hasn't made any deposits.
Widget now shows "$0", as it should, if the user hasn't made any deposits.
-

Fix total staked loader for users with no deposits

---

package-lock.json
package.json
src/components/NFTMedia/index.tsx

NFTMedia was previously relying on IPFS to grab MIME type. IPFS is less reliable than Cloudinary, so we should use Cloudinary as our source of MIME type.
Further adjustments to logic will be needed, but this works as a bandaid.

Release 0.11.3 - MIME type hotfix

---

package.json
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx

**Old behaviour:**
On smaller breakpoints, loading spinners weren't being hidden.
**New behaviour:**
Spinners for hidden columns are actually hidden.

Hide loading spinners on smaller breakpoints

---

src/components/ConnectToWallet/ConnectToWallet.tsx
src/components/ConnectToWallet/Wallet.module.scss
src/components/ConnectToWallet/utils.ts
src/containers/PageContainer/index.tsx

[Associated Notion Card](https://www.notion.so/rational-nomads/67a5d1b61d4146f491d5996a17b14a81?v=4f04ed31a23340bfbbdc5560502bc429&p=ef867c85e24a4a48a58208dc23fcc0c5)
-----
1. When disconnecting from metamask wallet the "Trying to reconnect metamask" and spinner has a line break. In addition, the wallet has already disconnected, therefore the message displayed is void. 
2. When connected to a wallet, the user can still select this option from the ConnectWallet component. 
1. Fixed line break in "Trying to connect to metamask". Added additional logic to determine if the wallet is reconnecting. Display 'Connect' button is wallet is disconnect and connection has been re-tried.
2. Disable current connected wallet from wallet options.

[Bug] Disconnecting wallet broken UI fix

---

.circleci/config.yml
package-lock.json
package.json
src/components/Cards/PreviewCard/Previewcard.test.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Team-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=585150edf7844452bfffc96f40737e87)
-----
BugFix
Circle Ci build fails on Preview Card Test
```A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks```
Circle Ci build passes
Added detectOpenHandles
Attempt to collect and print open handles preventing Jest from exiting cleanly. Use this in cases where you need to use --forceExit in order for Jest to exit to potentially track down the reason. This implies --runInBand, making tests run serially. Implemented using [async_hooks](https://nodejs.org/api/async_hooks.html).
Added maxWorkers
Alias: -w. …

Circle CI build failing fix

---

src/lib/providers/SubgraphProvider.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=3d3ca539b413421d9760edf557cce130)
-----
Cache data may be loss - existing and incoming 
Warning resolved by adding typePolicies to InMemoryCache
My Findings: 
From my understanding, this warning occurs because there is no explicit id or _id property and in Apollo Client 3 the inMemoryCache does not create a fallback fake identifier to normalise the data.
From [Apollo Docs](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#configuring-merge-functions-for-types-rather-than-fields): 
*If you define a merge function for a field, the cache calls that function whenever the field is about to be written with an incoming value (such as from your GraphQL server). When the …

Investigate and resolve ‘Cache data may be lost when replacing domains field of a Query object’ error

---

src/components/Banners/NextDrop/NextDrop.js
src/components/Confirmation/Confirmation.tsx
src/components/MintPreview/MintPreview.tsx
src/components/Notification/Notification.tsx
src/components/NotificationDrawer/NotificationDrawer.tsx
src/components/SearchBar/SearchBar.js
src/components/TransferPreview/TransferPreview.tsx
src/containers/PageContainer/elements/Header/elements/SearchDomains/SearchDomains.tsx
src/containers/flows/MakeABid/MakeABid.tsx
src/containers/flows/MintNewNFT/MintNewNFT.tsx
src/containers/legacy/Enlist/Enlist.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/PageHeader/PageHeader.tsx
src/containers/other/Request/Request.tsx

[Associated Notion Card](https://www.notion.so/dApp-Core-Product-Board-e96437225e264ae8ae8d46ca5f4d7b35?p=6a9d95a5d71b4e8fa615db1a4f25d810)
-----
Elements with the ```blur``` class had a transparency issue on firefox browser.
Added ```background-primary``` to each element with the blur class

Firefox browser backgrounds fix

---

src/containers/other/NFTView/NFTView.constants.tsx
src/containers/other/NFTView/NFTView.tsx
src/containers/other/NFTView/assets/transfer.svg
src/containers/other/NFTView/components/NFT.module.scss
src/containers/other/NFTView/components/NFT.tsx

[Associated Notion Card](https://www.notion.so/Move-Transfer-Ownership-button-in-NFT-View-to-the-dot-dropdown-in-top-right-corner-4ac0a8a30db64b69a470e168558bb5e2)
-----
Feature (small tweak)
Transfer Ownership button was a lonely button underneath the prices.
Now Transfer Ownership button gets to hang out with its friends in the action dropdown. Much nicer UX! This matches the Figma frame linked in the Notion card.

feat: Move Transfer Ownership button to dropdown

---

src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/containers/Tables/SubdomainTable/SubdomainTableRow.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Fix-missing-subdomain-table-buttons-eeba1de0297d4e81a067026823152347)
-----
Bugfix
Bid button wouldn't show up for domains that had `metadata.isBiddable = undefined`.
Adjusted logic so that internal `isBiddable` is `isBiddable = is biddable true or undefined`.

fix: show bid button by default

---

src/App.tsx
src/lib/hooks/sdk/useZnsSdk.tsx
src/lib/providers/ZnsSdkProvider.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Use-Context-API-for-SDK-9eab3ba31e114d009d5d528567a20e70)
-----
Refactoring
The SDK was just inside a custom hook in a `useMemo`, with the intention of the `useMemo` memo-ising the SDK instance and returning the same object every time it's called. However, creating a new instance of `useZnsSdk` also creates a new instance of the `useMemo`, and so the SDK gets reinitialised.
We're using context API for the SDK now so it just gets initialised once, rather than every time it's needed.

refactor: Use context API for SDK use

---

src/containers/flows/BuyNow/index.tsx
src/containers/flows/SetBuyNow/index.tsx
src/lib/hooks/useMetadata.ts

[Associated Notion Card](https://www.notion.so/zerotech/Metadata-not-being-parsed-in-two-spots-b6e0df1465f34ac281d9d72e517e7829)
-----
Bugfix/refactoring
`SetBuyNow` and `BuyNow` modals weren't properly parsing metadata.
`SetBuyNow` and `BuyNow` now use `getMetadata` to retrieve metadata.

fix(buy-now): Use standardised getMetadata method

---

src/containers/staking/DepositTable/DepositTable.helpers.ts

Note: do not merge until this has design team's approval
[Associated Notion Card](https://www.notion.so/zerotech/Change-deposit-pool-header-to-better-reflect-functionality-6ae1147a4ceb4f5b934dc6ed13a862a9)
-----
Feature
"Date Staked" on the Deposits table was a misleading header - the column actually represents "Date Claimed".
Switched header to "Date Claimed".
There is no need to check the preview build of this one - just check out the screenshot below:
In the next iteration, we should get pull in the actual date of stake. This is temporary.

feat: change "Date Staked" to "Date Claimed" in Deposits table

---

package-lock.json
package.json
src/containers/staking/DepositTable/DepositTable.helpers.ts

[Release Card](https://www.notion.so/zerotech/0-13-2-802575e443cb4d58a1ec6c9476fb1800)
This release sees one hotfix, and one small UX change:
- Bumped SDK version to handle domains with > 500 subdomains (`wilder.wheels.genesis`, for example) [[Notion Card]](https://www.notion.so/zerotech/Bump-SDK-version-for-wilder-wheels-gensis-fix-85236bb7eb1e40eba9c14c211addb7ef)
- Changed "Date Staked" to "Date Claimed" on My Deposits table [[Notion Card]](https://www.notion.so/zerotech/Change-deposit-pool-header-to-better-reflect-functionality-6ae1147a4ceb4f5b934dc6ed13a862a9)

Release 0.13.2

---

package-lock.json
package.json
src/components/NFTMedia/index.tsx
src/constants/ipfs.ts
src/lib/hooks/useDomainMetadata.tsx
src/lib/hooks/useZnsDomain.tsx
src/lib/ipfs.ts
src/lib/metadata.ts

[Associated Notion Card](https://www.notion.so/zerotech/0-13-3-448d87bccf944f7ea8fdfce91e201146)
Fixes a bug where the dApp would not load in some regions. This is because Fleek is/was down, so we have temporarily change our IPFS gateway to `ipfs.io`. This is a bandaid, we need to iterate on this.

Release 0.13.3

---

src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableRow.tsx
src/containers/lists/BidList/BidList.constants.ts
src/containers/lists/BidList/BidList.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=fea194c799784b5488ee94c643d879ef)
-----
- User is able to select bids they have made and open the accept bid flow.
- It is not obviously indicated that certain bids are user previous bids
- When a user can Accept Bids from the Bid List, we should filter out their own bids.
- When a user is not able to Accept Bids from the Bid List, we should not filter out their own bids.
- Text to indicate users bids
[Loom Walk through](https://www.loom.com/share/c0aef17a67f04b3db2a5815095070a1e)

hotfix: Filter Bids in Bid List when used can Accept Bids - Display all by default

---

src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.constants.ts
src/containers/Tables/OwnedDomainsTable/OwnedDomainsTable.utils.ts
src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableRow.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=6c6272a340f54080998cb1225b1cdfab)
-----
Dropdown options include 'View Bids' when there are no bids.
Dropdown options include 'View Bids', only when there are bids on the domain.
[Loom Video](https://www.loom.com/share/be83212752854387981806e906b3ad49)

fix: add rule to display ‘View Bids’ option when no bids (Profile - Your Domains)

---

src/components/Cards/ImageCard/ImageCard.module.scss
src/components/Cards/ImageCard/ImageCard.tsx
src/constants/aspectRatios.ts
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/lib/utils/domains.test.ts
src/lib/utils/domains.ts

_Apologies for the strange wordy title_
[Associated Notion Card](https://www.notion.so/zerotech/In-grid-view-the-images-cover-the-domain-details-2d5a57e2adf84139af148c57564d3520)
-----
Feature
- Grid card aspect ratios weren't being applied
- Grid card loading spinners were incorrectly positioned
The two problems in section 3 are now fixed.
There's a Loom in the Notion card explaining how to check this!

feat: Domain table grid card image aspect ratios

---

src/components/Cards/ImageCard/ImageCard.module.scss
src/containers/Tables/OwnedDomainsTable/OwnedDomainsTableCard.tsx
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx

[Associated Notion Card](https://www.notion.so/zerotech/neo-In-general-seems-to-be-loading-very-slow-7ac7b2b966754790b875a4a3b23987df)
-----
Bugfix
1. Table cards weren't using Cloudinary, and instead were loading assets straight from IPFS. This was incredibly slow, for obvious reasons.
2. Table card images weren't being vertically aligned.
1. Table cards now use Cloudinary to load assets.
2. Table card images are now vertically aligned.

fix: some assets not using Cloudinary

---

src/components/ArrowLink/ArrowLink.tsx
src/containers/other/NFTView/elements/TokenHashBoxes/TokenHashBoxes.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=4bbbcd19ad9045c980f2873d5e094ad0)
-----
Metadata links on nft view page were not redirecting to correct url
Redirect now goes to correct url
https://user-images.githubusercontent.com/39112648/166142824-fbdf296c-ea34-46d0-ad62-8fd4a3155ec2.mov

bug: fix for metadata link in NFT View routing 

---

src/containers/DAO/pages/DAOPage/hooks/useAssets.ts

When loading asset data from cache, state updates weren't triggering properly in anything consuming useAssets.ts
[Associated Notion Card](https://www.notion.so/zerotech/neo-Bug-Switching-from-grid-to-list-view-on-DAOs-changes-total-amount-in-DAO-summary-Ethan-couldn-3df6a97889634bb7885a723f3e8d14e1)
-----
Bugfix
Steps to recreate bug (on `develop`):
1. Navigate to DAOs <- asset totals are summed correctly
2. Navigate away from DAOs (i.e. to Market)
3. Navigate back to DAOs <- asset totals aren't summed correctly 
Asset totals will now sum correctly no matter what context you're arriving from.

fix(use-assets): asset totals not summing properly

---

src/containers/PageContainer/elements/Header/elements/SearchDomains/SearchDomains.constants.ts
src/containers/PageContainer/elements/Header/elements/SearchDomains/SearchDomains.tsx
src/lib/useDomainSearch.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=31ebe6869b104579b43f917afb4cb1a6)
-----
- bugfix
When entering _wilder_ into the search bar no results are displayed. 
When entering _wilder_ into the search bar matching results are displayed.

fix: display domain results when searching Wilder

---

src/containers/DAO/pages/DAOList/DAOTable/DAOTableRow.module.scss
src/containers/staking/DepositTable/DepositTableRow.module.scss
src/containers/staking/StakePoolTable/StakePoolTableRow.module.scss

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=3140736db7a142ce994e5d208a9b8995)
-----
DAO, Staking and Deposits table rows had a different background hover colour to market.
All table rows now have the correct hover background colour.

fix: update hover colour for DAO, Staking and Deposit tables

---

src/components/Preview/Preview.tsx
src/containers/cards/CurrentDomainPreview/CurrentDomainPreview.tsx
src/lib/hooks/useZnsDomain.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Domain-metadata-held-up-on-domains-with-a-lot-of-subdomains-40a861bfd30a456a995b79469fa3103a)
-----
Bugfix
On domains with large subdomains, subdomain loading takes a while. Previously, metadata didn't resolve until all data resolved, so in the case of domains with lots of subdomains, metadata wouldn't show up for a long time.
Decoupled the metadata and subdomain loading.

fix(current-domain): subdomain loading halting metadata loading

---

src/containers/flows/SetBuyNow/SetBuyNow.tsx
src/containers/other/NFTView/NFTView.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Projects-e96437225e264ae8ae8d46ca5f4d7b35?p=d25cd75bde2544819151d2a5cfc1ea5f)
-----
Edit buy now button was broken on NFTView - three dot dropdown option list. 
The modal header was misleading, stating 'Set Buy Now' rather than 'Edit Buy Now'
Edit buy now button works as expected.
Modal header will display Edit or Set

fix: Fix broken edit buy now button and modal header

---

package.json
src/components/Tables/GenericTable/GenericTable.tsx

[Associated Notion Card](https://www.notion.so/zerotech/Domains-with-grid-by-default-set-to-false-are-showing-list-view-on-mobile-instead-of-grid-0076956b0e094dfe9ab33a62e8b92d78)
-----
Bugfix
- Open http://app.wilderworld.com on small breakpoint
- Navigate to `wilder.wheels.genesis`
- This domain will load in list view despite small breakpoint
GenericTable considers screen size when initialising `is grid view`.

fix(generic-table): grid view default settings showing list view on mobile for some domains

---

src/containers/Tables/SubdomainTable/SubdomainTableCard.constants.ts
src/containers/Tables/SubdomainTable/SubdomainTableCard.module.scss
src/containers/Tables/SubdomainTable/SubdomainTableCard.tsx
src/containers/flows/BuyNow/BuyNowButton.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Team-Dash-78b824c0cd0e46c59c19dfe103ae929a?p=6c1b4974d3244cfbb31deabc5a2f91e6)
-----
- feature
When buy now has been set for a domain, the buy now button was not visible in grid view.
When buy now has been set for a domain, the buy now button is now visible in grid view.

feat: enable buy now button on table card - subdomain table

---

src/containers/other/NFTView/elements/DomainSettings/DomainSettings.constants.tsx
src/containers/other/NFTView/elements/DomainSettings/DomainSettings.tsx
src/containers/other/NFTView/elements/DomainSettings/elements/DomainSettingsFooter/DomainSettingsFooter.tsx
src/containers/other/NFTView/elements/DomainSettings/elements/DomainSettingsFooter/_domain-settings-footer.scss
src/containers/other/NFTView/elements/DomainSettings/hooks/useDomainSettingsHandlers.tsx

[Associated Notion Card](https://www.notion.so/zerotech/dApp-Team-Dash-78b824c0cd0e46c59c19dfe103ae929a?p=fadae80ffe704b338f3edaf9de813c25)
-----
- feature (add on to previous feature)
When user can't unlock metadata a warning message is displayed that doesn't provide any detail as to why they can't unlock. 
When locking metadata, the user can click to bring up the warning message but the success message persists.
Detailed message is now displayed when the user is unable to unlock the metadata.
Simple message is displayed when the user is able to unlock the metadata but currently locked.
Remove any other messages that are being displayed when warning message is triggered.
Display unlock button after locking and clicking the body of the domain settings modal.
Also extracted some hard coded …

feat: update domain warning message text and conditions

---

src/containers/flows/MakeABid/MakeABid.tsx

[Associated Notion Card](https://www.notion.so/zerotech/0-17-0-zAuction-2-1-network-switcher-a2c4a3409df541a197682d740babc572?p=3820b5bbfde946d0ba0a294000bff4f1)
-----
Success step of place a bid flow does not handle the modal closing when selecting 'Finish' button.
Clicking 'Finish' button will now close the modal and refetch bid data.
Fix:
https://user-images.githubusercontent.com/39112648/180021369-c404afac-21c2-4496-b28d-ed722180a8e6.mov

fix: Bid Table (Your Bids) - handle close modal events when successfully placing a bid

---

src/containers/DAO/pages/Container.module.scss
src/containers/DAO/pages/DAOPage/DAOPage.module.scss
src/containers/DAO/pages/DAOPage/DAOPage.tsx
src/containers/DAO/pages/DAOPage/Proposals/CreateProposal/CreateProposal.module.scss
src/containers/DAO/pages/DAOPage/Proposals/CreateProposal/CreateProposal.tsx
src/containers/DAO/pages/DAOPage/Proposals/CreateProposal/hooks/useCreateProposal.ts
src/containers/DAO/pages/DAOPage/Proposals/ProposalDetail/ProposalDetail.tsx
src/lib/dao/hooks/useDao.ts
src/lib/hooks/useBalance.ts

[Associated Notion Card](https://www.notion.so/zerotech/Prevent-users-not-holding-voting-token-from-accessing-Create-Proposal-1cdea0363c9e4ebe9b97f37196535193)
-----
Feature
Users who were not holding the DAO's voting token were able to access the Create Proposal flow.
The UI prevents users who are not holding the DAO's voting token from accessing the Create Proposal flow. It does this by:
1. Check voting token balance on Proposals page before showing "New Proposal" button
2. Check voting token balance on Create Proposal page - show error message if no balance

feat: users not holding voting token should be blocked from create proposal page

---

src/components/SideBar/SideBar.utils.ts

[Associated Notion Card](https://www.notion.so/zerotech/Wilder-logo-resetting-on-app-change-6f3ad6f5ac7549df90301a2215af11c2)
-----
Feature
Logo in the sidebar was changing when switching between apps on the WWMM. In the WWMM, the logo should always be the WW logo.
Logo doesn't change on WWMM.

fix: wilder logo resetting on app change

---

package-lock.json
package.json
src/containers/DAO/pages/DAOPage/Proposals/Proposals.helpers.ts

- Bugfix
Proposal status displaying as `Failed`. These are incorrect status'.
`canExecute` to be replaced in approved or denied status condition.
Proposal status displaying as `Approved` or `Denied`. These are the correct status'.
`canExecute` has been removed and the condition to determine status has been updated.
Incorrect Status (BEFORE FIX)
Correct Status (AFTER FIX)
As shown in zOS

fix: incorrect proposal status' - improve status format logic

---

src/App.tsx

Fixes the pool redirect in `zApp-Staking`. It would be good to fix this in `zApp-Staking`, however, we want to keep scope as small as possible as this app will be deprecated in the not-so-distant future.

fix: pool link redirect

---

package-lock.json
package.json
vite.config.ts

chore: bump zapp-daos (`0.18.1` -> `0.18.2`)
